// MOCK ANALYSIS - for testing the flow without Gemini API
export async function analyzeVehicleDamage(images, vehicleInfo, geminiApiKey) {
  // Simulate processing delay
  await new Promise(resolve => setTimeout(resolve, 2000));

  return {
    damages: [
      {
        part_name_en: 'Hood',
        part_name_ar: 'كبوت',
        damage_type: 'Clear dent',
        confidence: 0.95,
        severity_label: 'Repair',
        price: 2800,
        is_ai_detected: true,
        partId: 'PT_0001',
        category: 'exterior_body',
        isSafety: false,
      },
      {
        part_name_en: 'Front Left Fender',
        part_name_ar: 'رفرف أمامي شمال',
        damage_type: 'Obvious scratch',
        confidence: 0.87,
        severity_label: 'Repair',
        price: 2000,
        is_ai_detected: true,
        partId: 'PT_0018',
        category: 'exterior_body',
        isSafety: false,
      },
      {
        part_name_en: 'Front Left Headlight',
        part_name_ar: 'فانوس أمامي شمال',
        damage_type: 'Definitely broken',
        confidence: 0.92,
        severity_label: 'Replace',
        price: 5600,
        is_ai_detected: true,
        partId: 'PT_0008',
        category: 'exterior_body',
        isSafety: true,
      },
    ],
    needs_check_parts: [
      {
        part_name_en: 'Front Right Door',
        part_name_ar: 'باب أمامي يمين',
        damage_type: 'Possible dent in panel',
        confidence: 0.65,
        reason_for_uncertainty: 'Could be optical illusion or lighting effect on door surface',
        severity_label: 'Repair',
        price: 1800,
        is_ai_detected: true,
        partId: 'PT_0005',
        category: 'exterior_body',
        isSafety: false,
      },
      {
        part_name_en: 'Windshield',
        part_name_ar: 'الزجاج الأمامي',
        damage_type: 'Suspected crack at edge',
        confidence: 0.55,
        reason_for_uncertainty: 'Crack may be dirt/reflection, visible only at certain angles',
        severity_label: 'Replace',
        price: 8500,
        is_ai_detected: true,
        partId: 'PT_0012',
        category: 'glass',
        isSafety: true,
      },
      {
        part_name_en: 'Front Bumper',
        part_name_ar: 'مصد أمامي',
        damage_type: 'Likely minor deformation',
        confidence: 0.60,
        reason_for_uncertainty: 'Minor surface irregularity, could be manufacturing variation',
        severity_label: 'Repair',
        price: 1500,
        is_ai_detected: true,
        partId: 'PT_0003',
        category: 'exterior_body',
        isSafety: false,
      },
    ],
    vehicleInfo,
    timestamp: new Date().toISOString(),
  };
}
